blog/urls.py
from django.conf.urls import url
from blog.views import * # 이렇게 수정하면 아래와 같이 views.~ 형식에서 views. 부분을 빼야 함
                         # bookmark.urls에서는 from . import views로 했으므로 views.~ 형식으로 사용해야 함
#  아래에서 blog/ 부분은 이미 처리되고 넘어온 상황임
urlpatterns = [

    # Example: /
    url(r'^$', PostLV.as_view(), name='index'),

    # Example: /post/ (same as /)
    url(r'^post/$', PostLV.as_view(), name='post_list'),

    # Example: /post/django-example/
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),

    # Example: /archive/
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),

    # Example: /2012/
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

    # # Example: /2012/nov/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),
    # # Example: /2012/11/
    # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostMAV.as_view(), name='post_month_archive'),

    # # Example: /2012/nov/10/
    url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    # # Example: /2012/11/10/
    # url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

    # Example: /today/
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),

    # /blog/tag/ URL 요청을 처리할 뷰 클래스 지정, 태그 클라우드 출력용 뷰
    # Example: /tag/
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),

    # /blog/tag/태그 이름/ 요청을 처리할 뷰 클래스 지정
    # r'...': 이스케이프되지 않는 raw 스트링임을 표시
    # [^/]+ : / 이외 문자가 한번 이상 반복
    # (?u)  : 앞의 표현식을 유니코드로 인식하라고 지정(주소창에 한글 입력 가능하도록)
    # Example: /tag/tagname
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),

    # Example: /search/  # ch09 1/1
    url(r'^search/$', SearchFormView.as_view(), name='search'),
]
# 위에서 지정한 name 항목을 템플릿에서 사용할 때에는 이름공간을 포함하여,
# blog:index, blog:post_list, blog:post_detail, blog:post_archive, ... 로 명시해야 함

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# static() 함수는 정적 파일 처리하는 뷰를 호출할 수 있도록 URL 패턴을 반환
from django.conf.urls.static import static                              # ch10 1/4
# settings 변수는 settings.py 모듈에서 정의한 항목들을 담고 있는 객체에 대한 참조
from django.conf import settings                                        # ch10 2/4

from mysite.views import HomeView
# 회원 가입 처리 뷰 임포트
from mysite.views import UserCreateView, UserCreateDoneTV         # ch11 1/2

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # 아래 인증 관련 3행 추가                                        # ch11 2/2
    # 장고 인증 URLconf를 인클루드하여 활용하는데,
    #   여기에 정의된 /login, /logout 등이
    #   실제로는 /accounts/login, /accounts/logout 등으로 처리됨
    url(r'^accounts/', include('django.contrib.auth.urls')),
    # 계정 가입 처리하는 URL
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    # 계정 가입 완료될 때 보여줄 URL
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),          # ch10 3/4

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)     # ch10 4/4
# 기존 urlpatterns에 static() 함수가 반환하는 URL 패턴을 추가
# static(prefix, view=django.views.static.serve, **kwargs)
# settings.MEDIA_URL = '/media/' 이런 URL 요청이 오면,
# django.views.static.serve() 뷰 함수가 처리하게 되어 있는데,
# 이 뷰 함수에 다음 인자를 전달함
# document_root = settings.MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}장고 웹 프로그래밍{% endblock %}</title>

{% load staticfiles %}
<link href="https://fonts.googleapis.com/css?family=Sunflower:300" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'css/base.css' %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

<div id="header">                                           <!-- ch11 div#header 수정 -->
    <h1 class="maintitle"><a href="{% url 'home' %}" id="toptitle">FUN Language</a></h1>
    {% if user.is_active %}
        <h4 class="welcome">환영,
            <strong>{% firstof user.get_short_name user.get_username %}</strong>님. /
            <a href="{% url 'password_change' %}">비밀번호 변경</a> /
            <a href="{% url 'logout' %}">로그아웃</a>
        </h4>
    {% else %}
        <h4 class="welcome">익명 손님. /
            <a href="{% url 'login' %}">로그인</a> /
            <a href="{% url 'register' %}">회원 가입</a>
        </h4>
    {% endif %}
</div>

<div id="menu">
    <li><a href="{% url 'home' %}">메인화면</a></li>
    <li>|</li>
    <li><a href="{% url 'bookmark:index' %}">수강신청</a></li>
    <li>|</li>
    <li><a href="{% url 'blog:index' %}">강의소개</a></li>
    <li>|</li>
    <li><a href="{% url 'photo:index' %}">강사소개</a></li>
    <li>|</li>

{#    <li><a href="#">추가&bigtriangledown;</a>#}
{#        <ul>#}
{#            <li><a href="#">책갈피</a></li>#}
{#            <li><a href="#">게시판</a></li>#}
{#	        <li><a href="#">사진첩</a></li>#}
{#        </ul>#}
{#    </li>#}
{#    <li><a href="#">편집&bigtriangledown;</a>#}
{#        <ul>#}
{#            <li><a href="#">책갈피</a></li>#}
{#            <li><a href="#">게시판</a></li>#}
{#	        <li><a href="#">사진첩</a></li>#}
{#        </ul>#}
{#    </li>#}

{#    <li><a href="{% url 'blog:post_archive' %}">저장소</a></li>#}
{#    <li>|</li>#}
    <li><a href="{% url 'blog:search' %}">검색</a></li>
{#    <li><a href="{% url 'admin:index' %}">관리자</a></li>#}
</div>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}                   <!--base.html을 상속받는다고 선언-->

{% block title %}장고 웹 사이트{% endblock %}    <!--title 블록 재정의-->

<!--정적 파일인 css 연결하기 위하여, staticfiles를 로드-->
{% load staticfiles %}
<!--extrastyle 블록을 재정의하여 추가적으로 home.css 연결-->
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}                         <!--content 블록 재정의-->

<div id="content_home">     <!--content_home 영역 정의-->

    <div id="homeimg">      <!--homeimg 영역 정의-->
        <!--<a href="/"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"/></a>-->
        <img src="{% static 'img/homebanner.png' %}" style="height:700px; width: 100%;"/>
{#        <h4 style="margin: 0;">장고 프레임워크로 개발한 웹 사이트입니다.</h4>#}
    </div>

    <div id="content">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/dajW9nfXLds"
                frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <h2>FUN Language만의 독자적 영어 클래스!</h2>
        <div id="compintro">
            <p id="compintrop">
                 <br>영어 공부에서 가장 중요한 것은<br>살아 있는 언어 데이터를 가능한 한 많이 모아두는 것입니다.<br><br>
                 영상을 보고, 듣고, 따라 말하고, 퀴즈를 풀며 다양하게 반복 훈련하는 트레이닝은<br>살아있는 언어를 빠른 시간에 가장 많이 내 것으로 만들 수 있는 최적의 프로그램입니다.<br><br>
                <b>FUN Language는 그러한 프로그램을 제공합니다!</b>
            </p>
        </div>
    </div>

    <div id="homeimg2">      <!--homeimg 영역 정의-->
        <!--<a href="/"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"/></a>-->
        <img src="{% static 'img/homebanner2.png' %}" style="width: 100%; height:730px;"/>
        <!--<h4 style="margin: 0;">장고 프레임워크로 개발한 웹 사이트입니다.</h4>-->
    </div>

{#    <hr style="margin: 5px 0;">     <!--그림 밑으로 5px 간격을 두고 수평선 넣기-->#}

{#    <h2>웹 앱 선택</h2>#}
{##}
{#    <table id="applist">#}
{#        <tr>#}
{#        <td><b><i><a href="{% url 'bookmark:index' %}">책갈피</a></i><b></td>#}
{#        <td>당신의 책갈피를 등록하고 다른 사람들과 공유할 수 있습니다. 어쩌구 저쩌구. 중얼중얼.</td>#}
{#        <td id="Edit"><i><a href="#">등록</a></i></td>#}
{#        <td id="Edit"><i><a href="#">편집</a></i></td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#        <td><b><i><a href="{% url 'blog:index' %}">게시판</a></i><b></td>#}
{#        <td>당신의 게시물을 등록하고 다른 사람들과 공유할 수 있습니다. 어쩌구 저쩌구.</td>#}
{#        <td id="Edit"><i><a href="#">등록</a></i></td>#}
{#        <td id="Edit"><i><a href="#">편집</a></i></td>#}
{#        </tr>#}
{##}
{#        <tr>#}
{#        <td><b><i><a href="#">사진첩</a></i><b></td>#}
{#        <td>당신의 사진을 등록하고 다른 사람들과 공유할 수 있습니다. 어쩌구 저쩌구.</td>#}
{#        <td id="Edit"><i><a href="#">등록</a></i></td>#}
{#        <td id="Edit"><i><a href="#">편집</a></i></td>#}
{#        </tr>#}
{#    </table>#}
</div>
{% endblock content %}

{% block footer %}                      <!--footer 블록 재정의-->
    <div id="footer"><br><br>
        상호: 주식회사 퀄슨&nbsp&nbsp|&nbsp&nbsp사업자번호: 120-86-87406&nbsp&nbsp|&nbsp&nbsp대표자명: 문예지&nbsp&nbsp|&nbsp&nbsp원격평생교육시설<br>
        주소: 서울특별시 종로구 세종대로 149 광화문빌딩 15층&nbsp&nbsp|&nbsp&nbspFax: 02-1522-0549<br>
        고객센터: 1522-0548 / 운영시간 9:00 ~ 18:00 (주말·공휴일 제외 / 점심시간 12:00 ~ 13:00)<br><br>
        TM & ⓒ 2018 Cartoon Network
        <!--<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Copyleft.svg/220px-Copyleft.svg.png" height="12" width="12" />-->
    </div>
{% endblock footer %}

templates/hometest.html
{% extends "base.html" %}                   <!--base.html을 상속받는다고 선언-->

{% block title %}home.html{% endblock %}    <!--title 블록 재정의-->

{% block content %}                         <!--content 블록 재정의-->
    <div id="content">
        This is CONTENT area.
    </div>
{% endblock content %}

{% block footer %}                          <!--footer 블록 재정의-->
    <div id="footer">
        This is FOOTER area.
    </div>
{% endblock footer %}